insert into RateChart(RATECHART_ID,year,ratecode,billcode,billrate,info) values(1,2021, 'GD1', 123, 73.62,'info');
insert into RateChart(RATECHART_ID,year,ratecode,billcode,billrate,info) values(2,2021, 'GD2', 160, 54.36,'info');
insert into RateChart(RATECHART_ID,year,ratecode,billcode,billrate,info) values(3,2021, 'GD3', 161, 41.21,'info');
insert into RateChart(RATECHART_ID,year,ratecode,billcode,billrate,info) values(4,2021, 'GD4', 126, 29.45,'info');

insert into REGION(REGION_ID, REGION_NAME) VALUES (1,'India');
insert into REGION(REGION_ID, REGION_NAME) VALUES (2,'US');

insert into SUBGROUP(SUBGROUP_ID, SUB_GROUP_NAME,REGION_ID) VALUES (1,'India-EAST',1);
insert into SUBGROUP(SUBGROUP_ID, SUB_GROUP_NAME,REGION_ID) VALUES (2,'India-WEST',1);
insert into SUBGROUP(SUBGROUP_ID, SUB_GROUP_NAME,REGION_ID) VALUES (3,'US-EAST',2);
insert into SUBGROUP(SUBGROUP_ID, SUB_GROUP_NAME,REGION_ID) VALUES (4, 'US-WEST',2);

insert into PROJECT(PROJECT_ID, DELIVERY_PROJECT_MANAGER, PROJECT_CODE, PROJECT_END_DATE, PROJECT_MANAGER, PROJECT_NAME, PROJECT_START_DATE,PROJECT_STAUS, SUBGROUP_ID)  values(1, 'Rama','Proj1','01/01/2022' ,'Sankar', 'Custom Build', '01/01/2021', 'Ok', 1);
insert into PROJECT(PROJECT_ID, DELIVERY_PROJECT_MANAGER, PROJECT_CODE, PROJECT_END_DATE, PROJECT_MANAGER, PROJECT_NAME, PROJECT_START_DATE,PROJECT_STAUS, SUBGROUP_ID)  values(2, 'Rama','Proj2','01/01/2022' ,'Sankar', 'Damco Build', '01/01/2021', 'Ok', 1);
insert into PROJECT(PROJECT_ID, DELIVERY_PROJECT_MANAGER, PROJECT_CODE, PROJECT_END_DATE, PROJECT_MANAGER, PROJECT_NAME, PROJECT_START_DATE,PROJECT_STAUS, SUBGROUP_ID)  values(3, 'Rama','Proj3','01/01/2022' ,'Sankar', 'APMM Build', '01/01/2021', 'Ok', 2);
insert into PROJECT(PROJECT_ID, DELIVERY_PROJECT_MANAGER, PROJECT_CODE, PROJECT_END_DATE, PROJECT_MANAGER, PROJECT_NAME, PROJECT_START_DATE,PROJECT_STAUS, SUBGROUP_ID)  values(4, 'Rama','Proj4','01/01/2022' ,'Sankar', 'SAP Build', '01/01/2021', 'Ok', 3);
insert into PROJECT(PROJECT_ID, DELIVERY_PROJECT_MANAGER, PROJECT_CODE, PROJECT_END_DATE, PROJECT_MANAGER, PROJECT_NAME, PROJECT_START_DATE,PROJECT_STAUS, SUBGROUP_ID)  values(5, 'Rama','Proj5','01/01/2022' ,'Sankar', 'Packaged Solution', '01/01/2021', 'Ok', 3);

insert into RESOURCE(RESOURCE_ID, EMPLOYEE_BAND,EMPLOYEE_CODE,EMPLOYEE_NAME,WORKING_PLACE) values(1, '7A', 'emp1', 'Sur1', 'Kol');
insert into RESOURCE(RESOURCE_ID, EMPLOYEE_BAND,EMPLOYEE_CODE,EMPLOYEE_NAME,WORKING_PLACE) values(2, '6A', 'emp2', 'Sur2', 'Kol');
insert into RESOURCE(RESOURCE_ID, EMPLOYEE_BAND,EMPLOYEE_CODE,EMPLOYEE_NAME,WORKING_PLACE) values(3, '8', 'emp3', 'Sur3', 'Delhi');
insert into RESOURCE(RESOURCE_ID, EMPLOYEE_BAND,EMPLOYEE_CODE,EMPLOYEE_NAME,WORKING_PLACE) values(4, '7b', 'emp4', 'Sur4', 'Hyd');


insert into INVOICECYCLE (INVOICECYCLE_ID,INVOICE_END_DATE,INVOICE_START_DATE,MONTH,NO_OF_WEEK_IN_CYCLE,TIME_SHEET_DUE_DATE,WEEK_NUMBER,YEAR) values(1,'2021-03-10','2021-03-10','Mar-21',5,'2021-03-10',12,2021);
insert into INVOICECYCLE (INVOICECYCLE_ID,INVOICE_END_DATE,INVOICE_START_DATE,MONTH,NO_OF_WEEK_IN_CYCLE,TIME_SHEET_DUE_DATE,WEEK_NUMBER,YEAR) values(2,'2021-03-10','2021-03-10','Apr-21',4,'2021-03-10',17,2021);
insert into INVOICECYCLE (INVOICECYCLE_ID,INVOICE_END_DATE,INVOICE_START_DATE,MONTH,NO_OF_WEEK_IN_CYCLE,TIME_SHEET_DUE_DATE,WEEK_NUMBER,YEAR) values(3,'2021-03-10','2021-03-10','May-21',5,'2021-03-10',21,2021);
insert into INVOICECYCLE (INVOICECYCLE_ID,INVOICE_END_DATE,INVOICE_START_DATE,MONTH,NO_OF_WEEK_IN_CYCLE,TIME_SHEET_DUE_DATE,WEEK_NUMBER,YEAR) values(4,'2021-03-10','2021-03-10','June-21',4,'2021-03-10',26,2021);

