apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: metricssubmission-build-and-deploy-pipeline
spec:
  workspaces:
    - name: git-source
      description: The git repo
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRepo
      description: Git repository name         
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
    - name: scan-ibm
      description: Flag indicating that a scan should be performed with IBM VA
      default: "true"    
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: code-test-and-scan
      taskRef:
        name: java-maven-sonar
      runAfter:
        - clone-repo
      params:
        - name: git-url
          value: "$(params.gitUrl)"
        - name: app-name
          value: "$(params.gitRepo)"
      workspaces:
        - name: source
          workspace: git-source    
    - name: source-to-image
      taskRef:
        name: kaniko
      runAfter:
        - code-test-and-scan
      workspaces:
        - name: source
          workspace: git-source
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
    - name: img-scan
      taskRef:
        name: ibm-img-scan
      runAfter:
        - source-to-image
      params:
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: $(params.imageTag)      
        - name: scan-ibm
          value: $(params.scan-ibm)          
    - name: deploy-to-cluster
      taskRef:
        name: deploy-using-kubectl
      runAfter:
        - img-scan        
      workspaces:
        - name: git-source
          workspace: git-source
      params:
        - name: pathToYamlFile
          value: $(params.pathToYamlFile)
        - name: imageUrl
          value: $(params.imageUrl)
        - name: imageTag
          value: $(params.imageTag)
        - name: imageDigest
          value: $(tasks.source-to-image.results.IMAGE-DIGEST)