apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener:  <appname>-github-listener-interceptor
  name: <appname>-github-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-<appname>-github-listener-interceptor